services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: newdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
    ports:
      3307:3306
    volumes:
      ./db:/docker-entrypoint-initdb.d
    network:
      mynetwork

  Web:
    image: phpMyAdmin:lts
    ports: 8080:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      ./db:/docker-entrypoint-initdb.d
    network:
      mynetwork